# Generated by Django 5.2.1 on 2025-05-25 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('university', models.CharField(max_length=100)),
                ('academic_year', models.IntegerField()),
                ('degree_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=20)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('languages', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
