# Generated by Django 5.2.3 on 2025-06-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("university", models.CharField(max_length=100)),
                ("academic_year", models.IntegerField()),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("graduate", "Graduate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nickname", models.CharField(max_length=30, unique=True)),
                ("languages", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
            ],
        ),
    ]
