# Generated by Django 5.2 on 2025-05-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamapplication",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="team.team",
            ),
        ),
        migrations.AlterField(
            model_name="categoryrole",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
