# Generated by Django 5.2.1 on 2025-06-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teamapplication_team_alter_categoryrole_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
