# Generated by Django 5.2.1 on 2025-06-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_alter_competition_subcategory'),
        ('team', '0003_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
    ]
