# Generated by Django 5.2.3 on 2025-06-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_competition_image_url'),
        ('team', '0004_alter_team_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AlterField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
            preserve_default=False,
        ),
    ]
