# Generated by Django 5.2.1 on 2025-06-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('team', '0003_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='room_name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='team.team'),
        ),
    ]
