# Generated by Django 5.2.3 on 2025-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_chatroom_room_name_chatroom_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='team',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(default='default_room', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
