# Generated by Django 5.2.3 on 2025-06-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_chatroom_team_chatroom_room_name'),
        ('team', '0005_remove_team_name_alter_team_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='room_name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='team.team'),
        ),
    ]
