# Generated by Django 5.2 on 2025-05-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('영상/미디어', 'Media'), ('컴퓨터/소프트웨어', 'Software'), ('경영/경제', 'Business'), ('자연과학', 'Science'), ('교육/사회문제', 'Education'), ('건축/도시/환경', 'Architecture'), ('디자인/예술', 'Design'), ('기획/아이디어', 'Idea'), ('기타', 'Etc')], default='기타', max_length=30)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
