# Generated by Django 5.2.3 on 2025-06-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("아이디어·창업·네이밍", "아이디어·창업·네이밍"),
                            ("사진·영상", "사진·영상"),
                            ("디자인·그림·웹툰", "디자인·그림·웹툰"),
                            ("문학·학술·공학", "문학·학술·공학"),
                            ("예체능·e스포츠", "예체능·e스포츠"),
                            ("기타", "기타"),
                        ],
                        default="기타",
                        max_length=20,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        choices=[
                            ("창업", "창업"),
                            ("아이디어", "아이디어"),
                            ("슬로건", "슬로건"),
                            ("네이밍", "네이밍"),
                            ("마케팅", "마케팅"),
                            ("사진", "사진"),
                            ("영상", "영상"),
                            ("포스터", "포스터"),
                            ("로고", "로고"),
                            ("상품", "상품"),
                            ("캐릭터", "캐릭터"),
                            ("그림", "그림"),
                            ("웹툰", "웹툰"),
                            ("광고", "광고"),
                            ("도시건축", "도시건축"),
                            ("논문", "논문"),
                            ("수기", "수기"),
                            ("시", "시"),
                            ("시나리오", "시나리오"),
                            ("공학", "공학"),
                            ("과학", "과학"),
                            ("음악", "음악"),
                            ("댄스", "댄스"),
                            ("e스포츠", "e스포츠"),
                            ("기타", "기타"),
                        ],
                        default="기타",
                        help_text="세부항목 분류 (e.g. 창업, 영상, 포스터 등)",
                        max_length=50,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("link", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
