# Generated by Django 5.2 on 2025-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
