# Generated by Django 5.2 on 2025-05-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_competition_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='subcategory',
            field=models.CharField(blank=True, help_text='세부항목 분류 (e.g. 창업, 영상, 포스터 등)', max_length=50, null=True),
        ),
    ]
