# Generated by Django 5.2 on 2025-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_competition_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='category',
            field=models.CharField(choices=[('아이디어·창업·네이밍', '아이디어·창업·네이밍'), ('사진·영상', '사진·영상'), ('디자인·그림·웹툰', '디자인·그림·웹툰'), ('문학·학술·공학', '문학·학술·공학'), ('예체능·e스포츠', '예체능·e스포츠'), ('기타', '기타')], default='기타', max_length=20, verbose_name='대분류'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('창업', '창업'), ('아이디어', '아이디어'), ('슬로건', '슬로건'), ('네이밍', '네이밍'), ('마케팅', '마케팅'), ('사진', '사진'), ('영상', '영상'), ('포스터', '포스터'), ('로고', '로고'), ('상품', '상품'), ('캐릭터', '캐릭터'), ('그림', '그림'), ('웹툰', '웹툰'), ('광고', '광고'), ('도시건', '도시건'), ('논문', '논문'), ('수기', '수기'), ('시', '시'), ('시나리오', '시나리오'), ('공학', '공학'), ('과학', '과학'), ('음악', '음악'), ('댄스', '댄스'), ('e스포츠', 'e스포츠'), ('기타', '기타')], help_text='세부항목 분류 (e.g. 창업, 영상, 포스터 등)', max_length=50, null=True, verbose_name='소분류'),
        ),
    ]
