# Generated by Django 5.2.3 on 2025-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_alter_competition_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
