# Generated by Django 5.2.3 on 2025-06-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nationality", models.CharField(max_length=50)),
                ("languages", models.JSONField(default=list)),
                ("interests", models.JSONField(default=list)),
                ("in_team", models.BooleanField(default=False)),
                (
                    "desired_partner",
                    models.CharField(
                        blank=True,
                        help_text="함께 팀을 하고 싶은 사람의 user_id",
                        max_length=30,
                    ),
                ),
                ("subcategory", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
