# Generated by Django 5.2.3 on 2025-06-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=50)),
                ('languages', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('in_team', models.BooleanField(default=False)),
                ('desired_partner', models.CharField(blank=True, help_text='함께 팀을 하고 싶은 사람의 user_id', max_length=30)),
                ('role', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_group_id', models.CharField(blank=True, max_length=64, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_requests', to='competition.competition')),
            ],
        ),
    ]
