# Generated by Django 5.2.1 on 2025-06-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingrequest',
            name='subcategory',
        ),
    ]
