# Generated by Django 5.2.1 on 2025-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_matchingrequest_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrequest',
            name='role',
            field=models.JSONField(default=list),
        ),
    ]
