# Generated by Django 5.2.1 on 2025-06-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_alter_matchingrequest_role'),
        ('team', '0002_teamapplication_team_alter_categoryrole_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='team.team'),
        ),
        migrations.AddField(
            model_name='matchingrequest',
            name='team_group_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
