# Generated by Django 5.2.3 on 2025-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_alter_matchingrequest_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingrequest',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='matchingrequest',
            name='team',
        ),
        migrations.RemoveField(
            model_name='matchingrequest',
            name='team_group_id',
        ),
        migrations.AddField(
            model_name='matchingrequest',
            name='subcategory',
            field=models.CharField(default='기타', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingrequest',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
