# Generated by Django 5.2.3 on 2025-06-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_competition_image_url'),
        ('matching', '0009_remove_matchingrequest_competition_and_more'),
        ('team', '0005_remove_team_name_alter_team_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingrequest',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='matchingrequest',
            name='competition',
            field=models.ForeignKey(default=486, on_delete=django.db.models.deletion.CASCADE, related_name='matching_requests', to='competition.competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchingrequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='team.team'),
        ),
        migrations.AddField(
            model_name='matchingrequest',
            name='team_group_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='matchingrequest',
            name='role',
            field=models.JSONField(default=list),
        ),
    ]
